name: flutter_hiodsdk
description: "flutter version of HIODSDK."
version: 0.0.1
homepage: https://github.com/fuzhu666/HIODSDK

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_hiodsdk
        pluginClass: FlutterHiodsdkPlugin
      ios:
        pluginClass: FlutterHiodsdkPlugin
